# Назва сайту
title: "Fate Core UA"

# Опис сайту
description: "Перекладена версія офіційного довідника правил Fate Core System."

# Тема, яку ви використовуєте (Doks)
remote_theme: getdoks/doks@1.6.0

# Базова URL-адреса (якщо сайт розміщується не в корені домену)
# Якщо ваш сайт розміщено за адресою "https://tar-asiy.github.io/fate_core_ua/", то baseurl має бути встановлено як "/fate_core_ua"
baseurl: "/fate_core_ua"  # Змініть на "" якщо сайт розміщується в корені

# Основний URL вашого сайту
url: "https://tar-asiy.github.io"

# Інші опції налаштування (опціонально)
# Наприклад, встановлення мовних параметрів, логотипу, навігаційного меню тощо
# markdown: kramdown
# highlighter: rouge
