# Назва сайту
title: "Fate Core UA"

# Опис сайту
description: "Перекладена версія офіційного довідника правил Fate Core System."

# Тема, яку ви використовуєте (Doks)
remote_theme: just-the-docs/just-the-docs

# Базова URL-адреса (якщо сайт розміщується не в корені домену)
# Якщо ваш сайт розміщено за адресою "https://tar-asiy.github.io/fate_core_ua/", то baseurl має бути встановлено як "/fate_core_ua"
baseurl: "/fate_core_ua"  # Змініть на "" якщо сайт розміщується в корені

# Основний URL вашого сайту
url: "https://tar-asiy.github.io"

# Налаштування навігації
aux_links:
  "GitHub": 
    - "https://github.com/tar-asiy/fate_core_ua"

# Налаштування пошуку (опціонально)
search_enabled: true

# Налаштування TOC
toc:
  enabled: true

# налаштовуємо кольори callouts і вимикаємо там заголовки
callouts:
  danger:
    color: red        # червоний для критичних попереджень
  warning:
    color: yellow     # жовтий для важливих попереджень
  note:
    color: blue       # синій для загальних приміток
  secondary:
    color: grey-dk    # світло-сірий для другорядних блоків
  important:
    color: purple     # фіолетовий для важливих повідомлень
  tip:
    color: green      # зелений для корисних порад
  example:
    color: grey-dk    # темно-сірий для прикладів
