# Назва сайту
title: "Fate Core UA"

# Опис сайту
description: "Перекладена версія офіційного довідника правил Fate Core System."

# Тема, яку ви використовуєте (Doks)
remote_theme: just-the-docs/just-the-docs

# Базова URL-адреса (якщо сайт розміщується не в корені домену)
# Якщо ваш сайт розміщено за адресою "https://tar-asiy.github.io/fate_core_ua/", то baseurl має бути встановлено як "/fate_core_ua"
baseurl: "/fate_core_ua"  # Змініть на "" якщо сайт розміщується в корені

# Основний URL вашого сайту
url: "https://tar-asiy.github.io"

# Налаштування навігації
aux_links:
  "GitHub": 
    - "https://github.com/tar-asiy/fate_core_ua"

# Налаштування пошуку (опціонально)
search_enabled: true

# Налаштування TOC
toc:
  enabled: true

# налаштовуємо кольори callouts і вимикаємо там заголовки
callouts:
  note:
    title: ""
    color: blue       # синій
  info:
    title: ""
    color: blue      # синій для інформації
  tip:
    title: ""
    color: green     # зелений для порад
  success:
    title: ""
    color: green     # зелений для успіху
  warning:
    title: ""
    color: red       # червоний для попереджень
  caution:
    title: ""
    color: red       # червоний для застережень
  danger:
    title: ""
    color: red       # червоний для небезпеки
  important:
    title: ""
    color: purple    # фіолетовий для важливого
  highlight:
    title: ""
    color: blue      # синій для виділення
  new:
    title: ""
    color: green     # зелений для нового
  secondary:
    title: ""
    color: blue      # синій для другорядного
  example:
    title: ""
    color: blue      # синій для прикладів
