# Назва сайту
title: "Fate Core UA"

# Опис сайту
description: "Перекладена версія офіційного довідника правил Fate Core System."

# Тема, яку ви використовуєте (Doks)
remote_theme: just-the-docs/just-the-docs

# Базова URL-адреса (якщо сайт розміщується не в корені домену)
# Якщо ваш сайт розміщено за адресою "https://tar-asiy.github.io/fate_core_ua/", то baseurl має бути встановлено як "/fate_core_ua"
baseurl: "/fate_core_ua"  # Змініть на "" якщо сайт розміщується в корені

# Основний URL вашого сайту
url: "https://tar-asiy.github.io"

# Налаштування навігації
aux_links:
  "GitHub": 
    - "https://github.com/tar-asiy/fate_core_ua"

# Налаштування пошуку (опціонально)
search_enabled: true

# Налаштування TOC
toc:
  enabled: true

# налаштовуємо кольори callouts і вимикаємо там заголовки
callouts:
  note:
    title: ""
    color: blue        # основний синій для загальних приміток (primary)
  info:
    title: ""
    color: teal       # бірюзовий для інформаційних блоків
  tip:
    title: ""
    color: brown      # коричневий для порад
  success:
    title: ""
    color: darkgreen  # темно-зелений для повідомлень про успіх
  warning:
    title: ""
    color: orange     # помаранчевий для попереджень
  caution:
    title: ""
    color: pink       # рожевий для застережень (ближче до danger)
  danger:
    title: ""
    color: red        # червоний для небезпеки
  important:
    title: ""
    color: purple     # фіолетовий для важливих повідомлень
  highlight:
    title: ""
    color: yellow     # жовтий для виділення
  new:
    title: ""
    color: lime       # світло-зелений для нового контенту
  secondary:
    title: ""
    color: lightblue  # світло-синій як другорядний варіант primary
  example:
    title: ""
    color: gray       # сірий для прикладів
