# Назва сайту
title: "Fate Core UA"

# Опис сайту
description: "Перекладена версія офіційного довідника правил Fate Core System."

# Тема, яку ви використовуєте (Doks)
remote_theme: vsoch/docsy-jekyll

# Базова URL-адреса (якщо сайт розміщується не в корені домену)
# Якщо ваш сайт розміщено за адресою "https://tar-asiy.github.io/fate_core_ua/", то baseurl має бути встановлено як "/fate_core_ua"
baseurl: "/fate_core_ua"  # Змініть на "" якщо сайт розміщується в корені

# Основний URL вашого сайту
url: "https://tar-asiy.github.io"

# Необхідні плагіни для remote_theme
plugins:
  - jekyll-remote-theme

# увімкнено опцію для відображення змісту
toc:
  enabled: true
  h_min: 1
  h_max: 3

# Інші опції налаштування (опціонально)
# Наприклад, встановлення мовних параметрів, логотипу, навігаційного меню тощо
# markdown: kramdown
# highlighter: rouge
