# Назва сайту
title: "Fate Core UA"

# Опис сайту
description: "Перекладена версія офіційного довідника правил Fate Core System."

# Тема, яку ви використовуєте (Doks)
remote_theme: just-the-docs/just-the-docs

# Базова URL-адреса (якщо сайт розміщується не в корені домену)
# Якщо ваш сайт розміщено за адресою "https://tar-asiy.github.io/fate_core_ua/", то baseurl має бути встановлено як "/fate_core_ua"
baseurl: "/fate_core_ua"  # Змініть на "" якщо сайт розміщується в корені

# Основний URL вашого сайту
url: "https://tar-asiy.github.io"

# Налаштування навігації
aux_links:
  "GitHub": 
    - "https://github.com/tar-asiy/fate_core_ua"

# Налаштування пошуку (опціонально)
search_enabled: true

# Налаштування TOC
toc:
  enabled: true

# вимикаємо заголовки callouts
callouts:
  note:
    title: ""
    color: blue
  warning:
    title: ""
    color: yellow
  danger:
    title: ""
    color: red
  info:
    title: ""
    color: purple
  tip:
    title: ""
    color: green
  important:
    title: ""
    color: blue
  new:
    title: ""
    color: green
  highlight:
    title: ""
    color: yellow
